# Generated by Django 5.2 on 2025-04-17 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='pickup_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='return_date',
            new_name='start_date',
        ),
    ]
