# Generated by Django 5.2 on 2025-04-24 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
    ]
