# Generated by Django 5.2 on 2025-05-23 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_remove_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Email',
            field=models.EmailField(blank=True, max_length=100),
        ),
    ]
